[wip] Updated deno to 1.6.2
replit/polygott pull request #189
Opened 2020-12-22 19:12 UTC by lunaroyster

Updates deno to the latest version.

2021-01-02 15:40 UTC, satyarohith commented on languages/deno.toml
> +  "curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr sh -s v1.6.2",
```suggestion
  "curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr sh -s v1.6.3",
```

2021-01-02 15:43 UTC, satyarohith requested changes

2021-01-02 15:43 UTC, satyarohith commented on languages/deno.toml
>    "npm i -g typescript-language-server@0.4.0 typescript@3.8.3"
```suggestion
  "npm i -g typescript-language-server@0.4.0 typescript@4.1.3"
```

2021-01-02 15:43 UTC, satyarohith commented on languages/deno.toml
>    "npm i -g typescript-language-server@0.4.0 typescript@3.8.3"
This is the version running on Deno `1.6.3`.

2021-01-02 22:13 UTC, Liamolucko commented
`deno lsp` was added in 1.6, it should probably be used instead of `typescript-language-server`.

2021-01-04 20:53 UTC, cbrewster approved these changes
⬆️ Have you tested this locally to make sure LSP still works?

2021-01-21 09:44 UTC, lunaroyster commented
Awesome, LSP's working now.

2021-01-21 09:44 UTC, merged